apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: nginx-repo
  namespace: flux-system
spec:
  image: ghcr.io/d33vliter/nginx
  interval: 10s
  secretRef:
    name: registry-secret  # Solo si es necesario
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: nginx-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nginx-repo
  filterTags:
    pattern: '.*-release'
  policy:
    semver:
      range: ">=1.0.0-release"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: update-nginx
  namespace: flux-system
spec:
  interval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./clusters/k3d-k3s-default/proyecto-nginx/deploy
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "Automated image update for nginx image to {{ .Values.image.tag }}"
    push:
      branch: main
