apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: nginx-repo
  namespace: flux-system
spec:
  image: ghcr.io/d33vliter/nginx
  interval: 10s
  secretRef:
    name: registry-secret  # Solo si es necesario
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: nginx-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nginx-repo
  filterTags:
    pattern: '.*-release'
  policy:
    semver:
      range: ">=1.0.0-release"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: update-nginx
  namespace: flux-system
spec:
  interval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./clusters/k3d-k3s-default/proyecto-nginx
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        Automated image update

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Changed.FileChanges -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $changes := .Changed.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
          Changes:
        {{- range $_, $change := $changes }}
            - {{ $change.OldValue }} -> {{ $change.NewValue }}
        {{ end -}}
        {{ end -}}
    checkout:
      ref:
        branch: main
    push:
      branch: flux-main
