apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  targetNamespace: cumbio
  interval: 1m
  path: "./deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
