apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  targetNamespace: cumbio
  interval: 10s
  path: "./clusters/k3d-k3s-default/proyecto-nginx/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  images:
    - name: ghcr.io/d33vliter/nginx
      newName: ghcr.io/d33vliter/nginx # {"$imagepolicy": "flux-system:nginx-policy:name"}
      newTag: 1.6.0-release # {"$imagepolicy": "flux-system:nginx-policy:tag"}
