apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cumbio
  name: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ghcr.io/d33vliter/nginx:latest
          ports:
            - containerPort: 80
