apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=ghcr.io/d33vliter/test-k9s/nginx
    argocd-image-updater.argoproj.io/nginx.update-strategy: semver
    argocd-image-updater.argoproj.io/nginx.version-constraint: ~1.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ghcr.io/d33vliter/test-k9s/nginx:ian-1.0  # Versión inicial
        ports:
        - containerPort: 80
    imagePullSecrets:
      - name: ghcr-secret
