apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/d33vliter/test-k9s.git'  # Cambia esto por tu repositorio
    targetRevision: HEAD
    path: nginx  # Cambia esto por la ruta donde está tu manifiesto
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncWindows:
      - kind: Allow
        schedule: "*/1 * * * *"  # Esto es un ejemplo de cron para cada minuto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Considera usar una versión específica de la imagen
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP  # Cambiar a LoadBalancer si necesitas exponer el servicio externamente
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
