apiVersion: apps/argoproj.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: nginx-image-update
  namespace: argocd  # Namespace donde tienes instalado el ArgoCD Image Updater
spec:
  git:
    repoURL: https://github.com/d33vliter/test-k9s.git  # URL de tu repositorio Git
    branch: main  # Rama donde est치n los manifiestos de tu aplicaci칩n
    path: nginx/# Ruta dentro del repositorio donde est치n los manifiestos de Nginx
  image:
    name: nginx  # Imagen de Nginx en Docker Hub
    tag: 1.21.6   # O la etiqueta de versi칩n que prefieras
