apiVersion: fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m
  path: ./nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-k9s-git  # Nombre de tu repositorio Git
  targetNamespace: nginx  # Namespace donde deseas desplegar nginx
