apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 1m
  path: "./clusters/k3d-k3s-default/nginx"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
