# ./.github/workflows/auto-pr.yaml
name: flux-main Auto-PR
on:
  create:
    branches: [flux-main]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Asegura que se obtiene el último commit

      - name: Get Last Commit Message
        id: commit
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          gh pr create \
            --repo=${GITHUB_REPO} \
            --head=flux-main \
            --base=main \
            --title="Pulling ${GITHUB_REF} into main" \
            --body="${{ github.event.workflow_run.head_commit.message }}" \
            --reviewer=d33vliter \
            --draft
