# .github/workflows/auto-pr.yaml
name: flux-main Auto-PR
on:
  pull_request:
    branches:
      - main  # Solo ejecuta cuando el PR tiene como destino el branch que decidas

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from flux-main
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" != "flux-main" ]]; then
            exit 1
          fi

  pull-request:
    needs: validate-branch
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          gh pr create \
            --repo=${GITHUB_REPO} \
            --head=flux-main \
            --base=main \
            --title="Auto PR: Flux changes to main" \
            --body="Merging flux-main into main" \
            --reviewer=d33vliter \
            --draft
