# ./.github/workflows/auto-pr.yaml
name: flux-dev Auto-PR
on:
  create:
    branches: [flux-dev]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # used implicitly by the gh CLI to authenticate with GitHub
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        gh pr create \
          --repo=${GITHUB_REPO} \
          --head=flux-dev \
          --base=dev \
          --title="Pulling ${GITHUB_REF} into dev" \
          --body="${{ github.event.head_commit.message }}" \
          --reviewer=d33vliter \
          --draft
